import api from "./api"; // Import your base api slice
import { BASE_URL } from "../../utils/constants";

const userAuthApi = api.injectEndpoints({
	endpoints: (builder) => ({
		// SIGN UP
		signup: builder.mutation({
			query: (userData) => ({
				url: BASE_URL + "/signup",
				method: "POST",
				body: userData,
			}),
			invalidatesTags: ["User"],
		}),

		// LOG IN
		login: builder.mutation({
			query: (credentials) => ({
				url: BASE_URL + "/login",
				method: "POST",
				body: credentials,
			}),
			invalidatesTags: ["User"],
		}),

		// LOG OUT
		logout: builder.mutation({
			query: () => ({
				url: BASE_URL + "/logout",
				method: "POST",
			}),
			invalidatesTags: ["User"],
		}),

		// GET CURRENT USER PROFILE (To check if user is logged in on refresh)
		getMe: builder.query({
			query: () => BASE_URL + "/me",
			providesTags: ["User"],
		}),
	}),
	overrideExisting: false,
});

// Export hooks generated by RTK Query
export const {
	useSignupMutation,
	useLoginMutation,
	useLogoutMutation,
	useGetMeQuery,
} = userAuthApi;

export default userAuthApi;
